site_name: Star Docs

theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: slate
      primary: 'blue grey'
      accent: 'amber'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - palette.switcher
    - palette.toggle

plugins:
  - search
  - glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true