site_name: Star Docs

theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: slate
      primary: 'blue grey'
      accent: 'amber'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - palette.switcher
    - palette.toggle

plugins:
  - search
  - glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  consent:
    actions:
      - accept
      - reject
    cookies:
      analytics: Microsoft Clarity
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as
      well as to measure the effectiveness of our documentation and whether
      users find what they're searching for. With your consent, you're
      helping us to make our documentation better.

copyright: >
  <a href="#__consent">Change cookie settings</a>