site_name: Star Docs
site_url: https://docs.sc
repo_url: https://github.com/arcodiant/StarDocs
repo_name: Give feedback & contribute
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: slate
      primary: 'blue grey'
      accent: 'amber'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.action.edit
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - palette.switcher
    - palette.toggle

plugins:
  - search
  - glightbox
  - macros

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  current_version: 3.24.3
  consent:
    actions:
      - accept
      - reject
    cookies:
      analytics: Analytics
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as
      well as to measure the effectiveness of our documentation and whether
      users find what they're searching for. With your consent, you're
      helping us to make our documentation better.

copyright: >
  <a href="#__consent">Change cookie settings</a>
  <div>This site created & maintained by <a href="https://robertsspaceindustries.com/citizens/WhiskoTangey">WhiskoTangey</a> and published under <a href="https://github.com/Arcodiant/StarDocs/blob/main/LICENSE">CC-BY-SA-4.0</a></div>